### PR TITLE
check for empty tag string

### LINKED ISSUE #32: Update for multiple docker tags broke existing functionality
The newest release seems to have broken the ability to build tag based on latest release version - my script hasn't changed but now it fails to build the tag for the docker container.

CURRENT OUTPUT:
Run mr-smithers-excellent/docker-build-push@master
  with:
    image: props
    registry: ***.dkr.ecr.us-east-2.amazonaws.com
    dockerfile: Dockerfile
  env:
    AWS_DEFAULT_REGION: us-east-2
    AWS_REGION: us-east-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Docker image name created: ***.dkr.ecr.us-east-2.amazonaws.com/props
Logging into ECR region us-east-2...
WARNING! Using -*** the CLI is insecure. Use --password-stdin.
Building Docker image: ***.dkr.ecr.us-east-2.amazonaws.com/props:

PREVIOUS OUTPUT:
Run mr-smithers-excellent/docker-build-push@master
  with:
    image: props
    registry: ***.dkr.ecr.us-east-2.amazonaws.com
    dockerfile: Dockerfile
  env:
    AWS_DEFAULT_REGION: us-east-2
    AWS_REGION: us-east-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Creating Docker image tag...
Docker tag created: v3.2.0
Docker image name created: ***.dkr.ecr.us-east-2.amazonaws.com/props:v3.2.0
Logging into ECR region us-east-2...
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Building Docker image: ***.dkr.ecr.us-east-2.amazonaws.com/props:v3.2.0

### PR DESCRIPTION
**Pull request by paretje**
Fix #32

### CODE REVIEW

File: src/docker-build-push.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ const processBuildArgsInput = buildArgsInput => {
 };
 
 const splitTags = stringTags =>
-  stringTags === null || stringTags === undefined ? undefined : stringTags.split(',').map(tag => tag.trim());
+  stringTags === null || stringTags === undefined || stringTags === '' ? undefined : stringTags.split(',').map(tag => tag.trim());
```
Comment (mr-smithers-excellent) [inline src/docker-build-push.js:23]: Please fix the `prettier` error here. Should appear in multiple lines, like this:

```
const splitTags = stringTags =>
  stringTags === null || stringTags === undefined || stringTags === ''
    ? undefined
    : stringTags.split(',').map(tag => tag.trim());
```

**Review by mr-smithers-excellent — CHANGES_REQUESTED** [review]
Thanks again for the PR here.  Looks like there's just one formatting error to be fixed and we can get this merged.

File: src/docker-build-push.js (hunk 1 above)
Comment (paretje) [reply src/docker-build-push.js]: Done

**Review by mr-smithers-excellent — APPROVED** [review]
